### ISSUE TITLE
Where is jupyter-desktop-server going?

### ISSUE THREAD

**Issue by Chilipp** [yuvipanda/jupyter-desktop-server#14]
Hey @yuvipanda! 

Thanks for this great package! It's a wonderful tool to demonstrate open-source desktop-applications! I would like to ask you about your aims with this software. Are there plans to make this a stable package with documentation, etc.? Does it make sense to contribute or is it just an intermediate product?

**Comment by yuvipanda** [comment]
Glad you like it, @Chilipp!

Absoluttely makes sense to contribute! It is already being used in prod in several places. I think just that me and @manics haven't had enough time...

Starting with an installer guide and then going from there would be hugely helpful. I can promise reviews...

Thanks for opening this!

**Comment by Chilipp** [comment]
Alright! I am happy to contribute :smiley_cat: I am also using it for [psy-view](https://github.com/psyplot/psy-view/) [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/psyplot/psy-view/master?urlpath=/desktop) and it is extremely helpful!

I'd setup the installation instructions for mybinder.org and provide a little demo. Or do you think it should be of generic nature about the local installation of the package?

**Comment by yuvipanda** [comment]
@Chilipp setting up instructions for mybinder.org set up would be a very welcome start! Local installation is more difficult anyway, so let's do that later.

**Comment by psychemedia** [comment]
One of the quickest ways to get started using the desktop server is to clone this repo and then start adding custom desktop environment files to it.

Yes, there is clutter in the Jupyter notebook file listing, but that's just clutter if you want to get up and running quickly.

To use this repo that way, it would be useful if it took the form of a [Github template repository](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository); folk could quick start build their own environments on top of it a bit more cleanly.

**Comment by Chilipp** [comment]
But usually you would want to add the binder config to your own source code repository, wouldn't you. A template repo would not work that way.

**Comment by psychemedia** [comment]
I'm not sure that I was thinking! I guess the idea is you just install this a package... Ignore me... having a moment!

**Comment by sebastian-luna-valero** [comment]
Hi,

I have a small JupyterHub deployment on-site and I would like to add `jupyter-desktop-server`.

I tried and failed with:

https://hub.docker.com/r/regiscely/jupyter-desktop-server

Adding this to my `config.yml`:
```
singleuser:
  image:
    name: jupyter/minimal-notebook
    tag: latest
  profileList:
    - display_name: "Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: true
    - display_name: "Jupyter Desktop Server"
      description: "Run XFCE on a JupyterHub."
      kubespawner_override:
        image: regiscely/jupyter-desktop-server:latest
```
But the `hook-image-puller` pod enters an error state due to the `image-pull-singleuser-profilelist-2` container being in a  `CrashLoopBackOff` state.

Any ideas?

Best regards,
Sebastian
